project:
  name: Equity Research News Tool
  description: A tool to fetch, summarize, and analyze news articles for equity research.

api_keys:
  openai:
    api_key: "your_openai_api_key_here"
  newsapi:
    api_key: "your_newsapi_key_here"

users:
  - username: rainbow
    password: Amoke_123

langchain:
  model: "gpt-3.5-turbo"
  temperature: 0.7
  max_tokens: 1500
  rate_limits:
    tokens_per_minute: 40000
    requests_per_minute: 3
    requests_per_day: 200
    tokens_per_day: 200000

streamlit:
  title: "Equity Research News Tool"
  sidebar_title: "Article Summaries"
  footer: "Powered by OpenAI and NewsAPI"

data:
  input_file: "C:/Users/admin/OneDrive/Desktop/llm project/equity_research_articles.txt"
  output_file: "C:/Users/admin/OneDrive/Desktop/llm project/output/summaries.txt"
